# Generated by Django 4.2.1 on 2023-05-30 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferListKierowca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data spisu')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='spisy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('pesel', models.CharField(blank=True, max_length=11, null=True, verbose_name='PESEL')),
                ('kk', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numer K/K')),
                ('birth_date', models.DateField(verbose_name='Data urodzenia')),
                ('comments', models.CharField(blank=True, max_length=100, null=True, verbose_name='Uwagi')),
                ('transfer_list', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfer_list', to='spis_kierowca.transferlistkierowca')),
            ],
        ),
    ]
