# Generated by Django 4.2.1 on 2023-06-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spis_kierowca', '0002_alter_transferdriver_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferdriver',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Imię'),
        ),
    ]
