# Generated by Django 4.2.1 on 2023-05-15 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Data zamówienia')),
                ('orderer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dirver_orders', to=settings.AUTH_USER_MODEL, verbose_name='Zamawiający')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('pesel', models.CharField(blank=True, max_length=11, null=True, verbose_name='PESEL')),
                ('kk', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numer K/K')),
                ('birth_date', models.DateField(verbose_name='Data urodzenia')),
                ('transfer_date', models.DateTimeField(blank=True, null=True, verbose_name='Data pobrania')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Data zwrotu')),
                ('comments', models.CharField(blank=True, max_length=100, null=True, verbose_name='Uwagi')),
                ('status', models.CharField(blank=True, choices=[('a', 'Oczekuje'), ('o', 'Wypożyczona'), ('r', 'Zwrócona'), ('e', 'Odrzucona')], default='a', max_length=1)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='kierowca.order', verbose_name='Zamówienie')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='drivers', to=settings.AUTH_USER_MODEL, verbose_name='Pobierający')),
                ('returner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers_returner', to=settings.AUTH_USER_MODEL, verbose_name='Zwracający')),
                ('transfering_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfering_drivers', to=settings.AUTH_USER_MODEL, verbose_name='Przekazano do')),
            ],
        ),
    ]
