# Generated by Django 4.2.1 on 2023-05-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kierowca', '0002_rename_order_driverorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'permissions': [('return_driver', 'Can return driver'), ('transfer_driver', 'Can transfer driver')]},
        ),
    ]
