# Generated by Django 4.1.7 on 2023-03-01 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0003_order_orderer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='files.order'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='responsible_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vehicles', to=settings.AUTH_USER_MODEL),
        ),
    ]
