# Generated by Django 4.1.7 on 2023-03-09 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0004_alter_order_orderer_alter_vehicle_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='returner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles_returner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
