# Generated by Django 4.1.7 on 2023-04-16 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0005_vehicle_returner_alter_vehicle_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='transfering_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfering', to=settings.AUTH_USER_MODEL),
        ),
    ]
