# Generated by Django 4.1.7 on 2023-04-20 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_vehicle_transfering_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'permissions': [('can_return', 'Can return files')]},
        ),
    ]
