# Generated by Django 4.1.6 on 2023-04-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_alter_vehicle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'permissions': [('can_return_vehicle', 'Can return files')]},
        ),
    ]
