# Generated by Django 4.1.6 on 2023-04-27 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0009_alter_vehicle_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(verbose_name='Data zamówienia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Zamawiający'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Uwagi'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='files.order', verbose_name='Zamówienie'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='responsible_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Pobierający'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data zwrotu'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='returner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles_returner', to=settings.AUTH_USER_MODEL, verbose_name='Zwracający'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tr',
            field=models.CharField(max_length=8, verbose_name='TR'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transfer_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data pobrania'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transfering_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfering', to=settings.AUTH_USER_MODEL, verbose_name='Przekazano do'),
        ),
    ]
