# Generated by Django 4.1.7 on 2023-04-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_alter_order_order_date_alter_order_orderer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Oczekuje'), ('o', 'Wypożyczona'), ('r', 'Zwrócona'), ('e', 'Odrzucona')], default='a', max_length=1),
        ),
    ]
