# Generated by Django 4.1.6 on 2023-05-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_alter_vehicle_tr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data zamówienia'),
        ),
    ]
