# Generated by Django 4.2.1 on 2023-06-23 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pojazd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='pojazd.order', verbose_name='Zamówienie'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Oczekuje'), ('o', 'Wypożyczona'), ('r', 'Zwrócona'), ('e', 'Odrzucona'), ('b', 'Bezzwrotnie')], default='a', max_length=1),
        ),
    ]
